### ISSUE TITLE
可不可以支持DTU网关设备

### ISSUE THREAD

**Issue by dargoner** [kerwincui/FastBee#11]
可不可以支持DTU网关设备

**Comment by kerwincui** [comment]
需要到2.0版本，预计是明年2月份左右，商业版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月1日(周四) 晚上11:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [kerwincui/wumei-smart] 可不可以支持DTU网关设备 (Issue #11)




 
可不可以支持DTU网关设备
