### ISSUE TITLE
建议增加涂鸦的云云对接的API？

### ISSUE THREAD

**Issue by junke** [kerwincui/FastBee#12]
看到这个项目，蛮惊喜的，很多东西都做了，建议增加涂鸦的云云对接的API，这样可以接入涂鸦生态的硬件，项目操作起来方便很多

**Comment by kerwincui** [comment]
目前正在接入智能音箱，主要是小度平台为主



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月17日(周三) 下午2:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [kerwincui/FastBee] 建议增加涂鸦的云云对接的API？ (Issue #12)




 
看到这个项目，蛮惊喜的，很多东西都做了，建议增加涂鸦的云云对接的API，这样可以接入涂鸦生态的硬件，项目操作起来方便很多

**Comment by junke** [comment]
百度平台也是支持蛮多硬件的，这个版本什么时候能发布呢？
