### ISSUE TITLE
用docker安装好各项服务后 java项目连不上EMQX，提示message=Not authorized to connect

### ISSUE THREAD

**Issue by zengcong90** [kerwincui/FastBee#14]
1.进入EMQX服务执行    ./bin/emqx_ctl users list  显示无用户
2. 执行  ./bin/emqx_ctl users add wumei-smart wumei-smart  添加用户 wumei-smart
3. 在EMQX控制台开启emqx_auth_http、emqx_web_hook插件
4. 重新启动java项目后连接正常
5. 本地测试也正常

**Comment by kerwincui** [comment]
emqx使用4.0版本，需要启用http认证和webhook插件，启用插件后重启后端就可以连接了
